### ISSUE TITLE
Why is FIELDS a 2d array?

### ISSUE THREAD

**Issue by iroskam** [ripple/ripple-binary-codec#54]
All of the leafs of the FIELDS property are single JSON objects.  It would be cleaner to have each of the named fields as properties of a single object identified by the FIELDS property. 

Example:

`"FIELDS": {
  "Generic":{
    "nth":0,
    "isVLEncoded":false,
    "isSerialized":false,
    "isSigningField":false,
    "type":"Unknown"
  },
  "Invalid":{
  ...
}`

Having FIELDS as nested arrays instead of objects requires deeper referencing to get to each field.  Having FIELDS as an object allows referencing to be strictly by field name.

Why is the FIELDS property in definitions.json a 2d array?

**Comment by sublimator** [comment]
They are presorted in their canonical order

**Comment by sublimator** [comment]
At least at the time I think that was the reason :) And it may or may not have been used. I think it was more something related to ripple-lib-java

**Comment by iroskam** [comment]
Thank you for the response.  It is always a chore trying to remember
architecture decisions from long ago.  I was just curious.  It seemed a
little odd to make FIELDS an array and all members arrays since all
other top level entries are objects.  If FIELDS was an object and all
members were objects each member could be referenced by name with the '.'
operator instead of iterating and inspecting.

Anyway, thank you for your work pulling all this out of SField.cpp.
definitions.json is being used as a starting point for serialization in
multiple language libraries.

**Comment by intelliot** [comment]
There's a Python serialization library that uses `definitions.json`, so we will most likely keep the format the same. However, we will look into the possibility of scripting the generation of the `definitions.json` file (by parsing code in rippled) so that new things (e.g. Tickets) can be automatically added in the future.

For example, Fields are from https://github.com/ripple/rippled/blob/develop/src/ripple/protocol/impl/SField.cpp
